config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :questions do
    resources :answers
  end
  root 'questions#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  validates :body, :question_id, presence: true

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  validates :title, :body, presence: true
  validates :title, length: { minimum: 5 } 
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @answer = Answer.new
  end

  def create
    @question = Question.find(params[:question_id])

    @answer = @question.answers.build(answer_params)
    if @answer.save
      redirect_to question_path(@answer.question_id)
    else
      render :new
    end
  end

  private

    def answer_params
      params.require(:answer).permit(:question_id, :body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create, :destroy]
  before_action :get_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def show
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      flash[:notice] = 'Your question successfully created.'
      redirect_to @question
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path
  end

  private

    def get_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:title, :body)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyStackOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/questions/index.html.slim
section id="container"
  table class="table table-striped table-hover"
    thead
      tr
        th 
        th 
    tbody
      p= link_to 'Ask question', new_question_path
      - @questions.each do |question| 
         tr  class="active"
          td = question.title
          td = question.body
          td = link_to 'Редактировать', edit_question_path(question)
          td = link_to 'Удалить', question_path(question), method: :delete, data: {confirm: 'Удалить?'} 

app/views/questions/new.html.slim
= form_for @question do |f|
 = f.label :title
 = f.text_field :title
 = f.label :body
 = f.text_field :body
 = f.submit 'Create'